#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TestyDroid.Android.Resource", IsApplication=false)]

namespace TestyDroid.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040001
			public static int OptionHostName = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int OptionPort = 2130968578;
			
			// aapt resource value: 0x7f040000
			public static int OptionRemoteServer = 2130968576;
			
			// aapt resource value: 0x7f040010
			public static int OptionsButton = 2130968592;
			
			// aapt resource value: 0x7f04000b
			public static int ResultFullName = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public static int ResultMessage = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public static int ResultResultState = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public static int ResultRunSingleMethodTest = 2130968586;
			
			// aapt resource value: 0x7f04000e
			public static int ResultStackTrace = 2130968590;
			
			// aapt resource value: 0x7f040006
			public static int ResultsFailed = 2130968582;
			
			// aapt resource value: 0x7f040003
			public static int ResultsId = 2130968579;
			
			// aapt resource value: 0x7f040007
			public static int ResultsIgnored = 2130968583;
			
			// aapt resource value: 0x7f040008
			public static int ResultsInconclusive = 2130968584;
			
			// aapt resource value: 0x7f040009
			public static int ResultsMessage = 2130968585;
			
			// aapt resource value: 0x7f040005
			public static int ResultsPassed = 2130968581;
			
			// aapt resource value: 0x7f040004
			public static int ResultsResult = 2130968580;
			
			// aapt resource value: 0x7f04000f
			public static int RunTestsButton = 2130968591;
			
			// aapt resource value: 0x7f040011
			public static int TestSuiteListView = 2130968593;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public static int options = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int results = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int test_result = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int test_suite = 2130837507;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public static int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public static int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
